### ISSUE TITLE
Neighbourhood Names not properly spatial joining

### ISSUE THREAD

**Issue by mnesca** [mnesca/wpg_transit_passups#1]
**Background needs:**
My original need is to _attach neighbourhood names_ - from the City of Winnipeg Neighbourhood shapefile - _to the point data set_ - in the transit pass-up data.

**Current Problem:**
I am currently trying to spatial join my neighbourhood shapefile with my transit dataset.  The code works, but i am receiving NAs under neighbourhood names and ID in my point dataset (transit dataset). 
![image](https://user-images.githubusercontent.com/51373047/79491370-fb618f00-7fe3-11ea-9a86-9bd7da83b1b0.png)

**Code I wrote:**
I made sure i matched my projections for both my shape file and my transit pass up data
```
# convert passup data frame into sf object
transitclean_sf <- transitdataclean %>%
  st_as_sf(
    coords = c("longitude", "latitude"),
    agr = "constant",
    crs = 26914,        # nad83 / Manitoba Projection
    stringsAsFactors = FALSE,
    remove = TRUE
  ) 

wpg_sf <- wpg %>%
  st_transform(crs = st_crs(transitclean_sf)) %>%   # convert to same projection as above
  select(id, name) 

latlong_in_wpg <- st_join(transitclean_sf, wpg_sf, join = st_within) 
```

**Speculation of Source of Problem:**
I speculate that during the transformation of the projection of my shape file (wpg_sf) somehow changed the geometry coordinates see below for before and after.
_Before (wpg):_
![image](https://user-images.githubusercontent.com/51373047/79495438-35359400-7fea-11ea-93ac-99908c00fee8.png)
_After (wpg_sf):_
![image](https://user-images.githubusercontent.com/51373047/79495520-55655300-7fea-11ea-9210-27aaf6d94bc2.png)
I have tried using the standard projection of 4326 in the original shapefile (wpg) and applying it to the point dataset (transitclean_sf) but then the join does not work. 

Any help appreciated -- ive been stuck on this problem for a couple weeks and cannot move forward in my project.  The rest of the code is located in the scripts folder under "transit_passup_cleandata.R"

Packages TAG: sf, tidyverse

**Comment by jlacko** [comment]
I believe your construction of `transitclean` data is needlessly complex - consider the code I have pull requested.

I have concentrated only on the key issue of joining transit data to Winnipeg neighborhoods, but that works.

The tricky parts were:
- filtering out illegal geometry from location
- applying st_as_sfc on the location column (it follows WKT logic) and assigning the result to geometry of the original data.frame; this will make it spatial
- assigning WGS84 as CRS of the points data (it has the look of GPS coordinates; this hunch was confirmed by the succesful spatial join afterwards)

And that was it. Transforming points to CRS of  the neighbourhoods and running st_join on the two objects was easy.

Let me know if this answers your problem

J.

**Comment by mnesca** [comment]
Thank you very kindly jlacko!

the code works and i have learned many lessons!
